### ISSUE TITLE
test run

### ISSUE THREAD

**Issue by cyanosoma01** [JesseKerkvliet/Bellerophon#2]
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -jN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -j1.
How can I fix it？

**Comment by JesseKerkvliet** [comment]
Hi,
I have updated the tool to include a local installation with conda. Although it's not a direct solution to this error, I hope it will stop popping up. Let me know if you still encounter it when using conda installation.
